## mini-projet:L'IA pour les mesures des champs électromagnétique
 

 
### Réalisr par:   mayssa merchaaoui

#### 2DNI2
    
  

In [1]:
%matplotlib inline
import pandas as pd
import pickle
#importation de la bibliothéque Random
from random import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#création d'un dataframe df permet de  lire le fichier initial
df=pd.read_csv('ANFR_Herault_Mesures_eq.csv',delimiter=';')
df.head()

Numéro de mesure  Longitude  Latitude  \
0               175    3.91611  43.58528   
1               180    4.04194  43.64694   
2               543    3.03167  43.36028   
3               545    3.03278  43.36167   
4               850    3.56444  43.64583   

                                    Position  Insee  \
0  03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1  04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2  03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3  03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4  03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   

                               Adresse                 Complément  \
0                           Mas de Gau                        NaN   
1  5539 Rue Lou Claou de la Oulivettas                        NaN   
2                 Chemin de Montfaucon  résidence de  Mme SOUTADE   
3                   Chemin de Quarante  résidence de  M. GONZALEZ   
4           480 Chemin de Pioch Courbi      Chez Mme et M. GALOIS   

   Code postal       Commune Date de mesure Mesure réalisée  \
0        34970        LATTES     06/12/2001    En extérieur   
1        34130      MUDAISON     06/12/2001    En extérieur   
2        34620  PUISSERGUIER     23/05/2002    En extérieur   
3        34620  PUISSERGUIER     23/05/2002    En extérieur   
4        34150        GIGNAC     10/10/2002    En extérieur   

              Rapport Conformité de la mesure  Niveau global  \
0  FicheMesure175.pdf                     Oui           0.00   
1  FicheMesure180.pdf                     Oui           0.00   
2  FicheMesure543.pdf                     Oui           0.54   
3  FicheMesure545.pdf                     Oui           0.20   
4  FicheMesure850.pdf                     Oui           0.53   

    Type d'environnement Laboratoire  
0                 Divers     SATELIT  
1                 Divers     SATELIT  
2                 Divers       APAVE  
3                 Divers       APAVE  
4  Rue / Route / Parking       APAVE

In [2]:
#création d'un dataframe df pour lire le fichier initial
df.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [3]:
# permet d'affecter un label à la dataframe ,par défaut =1 
df=df.assign(target=1)
print(df)

      Numéro de mesure  Longitude  Latitude  \
0                  175    3.91611  43.58528   
1                  180    4.04194  43.64694   
2                  543    3.03167  43.36028   
3                  545    3.03278  43.36167   
4                  850    3.56444  43.64583   
...                ...        ...       ...   
1819            159667    3.87667  43.59809   
1820            160107    3.86363  43.60516   
1821            160146    3.22983  43.36141   
1822            160274    3.86367  43.60505   
1823            160278    3.48046  43.28074   

                                       Position  Insee  \
0     03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1     04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2     03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3     03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4     03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   
...                                         ...    ...   
1819  03° 52' 36.02'' Est, 43

In [4]:
# permet de lire toutes les colonnes avec la nouvelle"target"
df.columns

Index(['Numéro de mesure', 'Longitude', 'Latitude', 'Position', 'Insee',
       'Adresse', 'Complément', 'Code postal', 'Commune', 'Date de mesure',
       'Mesure réalisée', 'Rapport', 'Conformité de la mesure',
       'Niveau_global', 'Type d'environnement', 'Laboratoire', 'target'],
      dtype='object')

#### **** j'ai changer la dataset de 900 ligne à 1800 ligne  et pour avoir la dataset equilibré cette fonction  permet de remplir les champs 'niveau_global' par des valeur compris entre [5.95,9]

In [5]:

def Niveau_global():
    for t in range(913,len(df)):
        df['Niveau_global'][t] = uniform(5.95 , 9) ;
                              
    print (df)

In [6]:
# permet d'afficher les colones du 'niveau_global'
Niveau_global()

      Numéro de mesure  Longitude  Latitude  \
0                  175    3.91611  43.58528   
1                  180    4.04194  43.64694   
2                  543    3.03167  43.36028   
3                  545    3.03278  43.36167   
4                  850    3.56444  43.64583   
...                ...        ...       ...   
1819            159667    3.87667  43.59809   
1820            160107    3.86363  43.60516   
1821            160146    3.22983  43.36141   
1822            160274    3.86367  43.60505   
1823            160278    3.48046  43.28074   

                                       Position  Insee  \
0     03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1     04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2     03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3     03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4     03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   
...                                         ...    ...   
1819  03° 52' 36.02'' Est, 43

<ipython-input-5-6da383d88023>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Niveau_global'][t] = uniform(5.95 , 9) ;


In [7]:
dfmay = pickle.load( open( "datasave.p", "rb" ) )

In [8]:
#cette fonction permet de donner à chaque niveau un target qui lui correspond
def target():
    for t in range(0,len(df)):
        if dfmay['Niveau_global'][t] > 6 :
            dfmay['target'][t] = 0
            print(dfmay['Niveau_global'][t]) 

In [9]:
#afficher les champs target
target()

9.63
8.44
8.03
9.06
9.05
6.65
15.66
25.39
10.33
9.1
6.98

<ipython-input-8-45978d6b53ae>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfmay['target'][t] = 0



21.03
10.57
8.52
7.1532902569207915
8.995334821434493
7.676068066937768
7.4828113607169655
7.927435297379683
6.765756439804388
7.30831603433809
7.557162545386263
8.873036795939065
8.787043835641997
6.333930561337732
7.765895749851952
7.996620522369533
6.927867592724793
8.539173785580028
7.850786836015891
8.047354958552107
8.228651617938752
6.98630416788007
6.422639393714548
8.362087234178675
6.159645083891389
8.329003656718575
6.15258913166735
8.82149829225252
8.859131170903972
6.177023659103554
8.978051630041698
7.4439941588116625
7.171360070592816
6.5023800078567
7.296653177880386
8.251182015596182
6.925311547183165
7.642538339165084
8.169918795233091
8.338776893137782
7.1541418461707185
8.120197261986082
6.186993409025945
8.681247493394748
7.874158110252298
8.75237156116297
8.885805571984374
8.738499997134516
7.164605782806823
6.303427618600799
7.621229147696644
7.397296615857787
6.1272299896703695
6.499894292556924
7.486938357516641
6.852627419596824
6.4406157682900895
8.559358423

8.002536704845811
8.238918466414656
6.829814313246266
7.628679402599489
7.173685373684494
6.522843469605457
6.168690443513405
7.185188129905711
8.007658522658026
7.9134404573095
6.069318511087075
6.451797691084285
6.007157375232712
7.831311599322207
6.590791329069185
7.0772480134950975
6.240272197791848
8.004346205478331
8.633217165201405
8.3724614989281
6.9199645957784925
7.583581721382222
6.059694053803026
6.109728771382957
8.342954170574181
6.523174271423467
8.06240994296839
8.89169949569083
8.87542005129042
8.855423404662007
8.825403580931662
8.001439760012504
6.4695912102108455
8.787600879179994
8.734299796015586
6.923778884185193
6.485624781626313
8.755752208663456
6.094732661499853
6.085862650131355
6.296744474090098
8.458656836697415
7.649394309963829
7.431466536779647
6.940574142164397
7.745168218030383
7.678357531902285
7.381100080128784
6.889141590878236
7.152599212405537
7.7451909347782255
6.385947642731183
7.368409449384075
7.082599576716811
6.349459324946744
6.06708734336

In [10]:
# permet d'afficher le nombre des lignes qui posséde un target 0 et celui avec un target 1
pd.crosstab(dfmay.target, "freq")

col_0   freq
target      
0        917
1        907

In [11]:
# afficher le 30 premiére ligne de data frame
dfmay.head(30)

Numéro de mesure  Longitude  Latitude  \
0                175    3.91611  43.58528   
1                180    4.04194  43.64694   
2                543    3.03167  43.36028   
3                545    3.03278  43.36167   
4                850    3.56444  43.64583   
5                851    3.56306  43.64806   
6                852    3.56306  43.64694   
7               1072    3.91611  43.58500   
8               1073    3.91667  43.58667   
9               1074    3.91889  43.58583   
10              1115    3.20806  43.34861   
11              1193    3.89750  43.63806   
12              1194    3.89778  43.63889   
13              1195    3.89889  43.63861   
14              1955    3.88556  43.71639   
15              2286    3.86944  43.60833   
16              2428    4.08361  43.55861   
17              2429    4.08361  43.55861   
18              3043    3.23056  43.36139   
19              3045    3.23028  43.36167   
20              3046    3.22861  43.36306   
21              3047    3.22917  43.36222   
22              3261    3.47833  43.30778   
23              3263    3.47750  43.30750   
24              3309    3.79389  43.48944   
25              3310    3.79389  43.48944   
26              3876    3.81139  43.64000   
27              3877    3.81139  43.64000   
28              3878    3.81111  43.64028   
29              3879    3.81167  43.63972   

                                     Position  Insee  \
0   03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129   
1   04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176   
2   03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225   
3   03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225   
4   03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114   
5   03° 33' 47.00'' Est, 43° 38' 53.00'' Nord  34114   
6   03° 33' 47.00'' Est, 43° 38' 49.00'' Nord  34114   
7   03° 54' 58.00'' Est, 43° 35' 06.00'' Nord  34129   
8   03° 55' 00.00'' Est, 43° 35' 12.00'' Nord  34129   
9   03° 55' 08.00'' Est, 43° 35' 09.00'' Nord  34129   
10  03° 12' 29.00'' Est, 43° 20' 55.00'' Nord  34032   
11  03° 53' 51.00'' Est, 43° 38' 17.00'' Nord  34057   
12  03° 53' 52.00'' Est, 43° 38' 20.00'' Nord  34057   
13  03° 53' 56.00'' Est, 43° 38' 19.00'' Nord  34057   
14  03° 53' 08.00'' Est, 43° 42' 59.00'' Nord  34014   
15  03° 52' 10.00'' Est, 43° 36' 30.00'' Nord  34172   
16  04° 05' 01.00'' Est, 43° 33' 31.00'' Nord  34344   
17  04° 05' 01.00'' Est, 43° 33' 31.00'' Nord  34344   
18  03° 13' 50.00'' Est, 43° 21' 41.00'' Nord  34032   
19  03° 13' 49.00'' Est, 43° 21' 42.00'' Nord  34032   
20  03° 13' 43.00'' Est, 43° 21' 47.00'' Nord  34032   
21  03° 13' 45.00'' Est, 43° 21' 44.00'' Nord  34032   
22  03° 28' 42.00'' Est, 43° 18' 28.00'' Nord  34003   
23  03° 28' 39.00'' Est, 43° 18' 27.00'' Nord  34003   
24  03° 47' 38.00'' Est, 43° 29' 22.00'' Nord  34333   
25  03° 47' 38.00'' Est, 43° 29' 22.00'' Nord  34333   
26  03° 48' 41.00'' Est, 43° 38' 24.00'' Nord  34172   
27  03° 48' 41.00'' Est, 43° 38' 24.00'' Nord  34172   
28  03° 48' 40.00'' Est, 43° 38' 25.00'' Nord  34172   
29  03° 48' 42.00'' Est, 43° 38' 23.00'' Nord  34172   

                                      Adresse  \
0                                  Mas de Gau   
1         5539 Rue Lou Claou de la Oulivettas   
2                        Chemin de Montfaucon   
3                          Chemin de Quarante   
4                  480 Chemin de Pioch Courbi   
5                                Vieux chemin   
6                  401 Chemin de Pioch Courbi   
7                 Château d'eau de Boirargues   
8       Avenue de la Mer - Garage Tunning XXS   
9                       Chemin des Mas de Gau   
10                          15 Rue des Cygnes   
11                256 Chemin du Château d'eau   
12                 50 Chemin du Château d'eau   
13                       Impasse de l'Oppudum   
14                     283 Rue de Montpellier   
15                             Cours Gambetta   
16                            140 Rue 

In [12]:

X=dfmay[['Numéro de mesure','Niveau_global']].to_numpy()
print(X)
y=dfmay['target'].to_numpy()
print(y)

[[1.75000000e+02 0.00000000e+00]
 [1.80000000e+02 0.00000000e+00]
 [5.43000000e+02 5.40000000e-01]
 ...
 [1.60146000e+05 7.40842051e+00]
 [1.60274000e+05 6.65445619e+00]
 [1.60278000e+05 7.24134460e+00]]
[1 1 1 ... 0 0 0]


In [13]:
#pour l'apprentissage ona diviser x en 'X_train', 'X_test' et y en 'y_train', 'y_test'
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [14]:
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#scaler.fit(X_train)
#from sklearn.neighbors import KNeighborsClassifier
#logreg1 = KNeighborsClassifier(n_neighbors = 2)
#classifier.fit(X_train, y_train)
from sklearn.linear_model import LogisticRegression 
#Create a l.Reg Classifier
logreg1 = LogisticRegression()
#Train the model using the training sets
logreg1.fit(X_train, y_train)
y_pred=logreg1.predict(X_test)

#### **** je faire un  teste avnec 3 algorthime  pour celle de deux algorithme de prediction (algorithme de KNN et algorithme  )il on donne des resultat inferieur a celle de regression logistique  

In [15]:
#afficher  la matrice de confusion
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[275   0]
 [  2 271]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       275
           1       1.00      0.99      1.00       273

    accuracy                           1.00       548
   macro avg       1.00      1.00      1.00       548
weighted avg       1.00      1.00      1.00       548

0.9963503649635036


test du modèle avec des nouvelles données

In [16]:
#création d'un nouveau dataframe pour faire un test 
df1=pd.read_csv('test-mesure.csv')


In [17]:
df1.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [18]:
#affecter un label à la dataframe qui est par défaut =1 
df1=df1.assign(target=1)
print(df1)

    Numéro de mesure  Longitude  Latitude  \
0                175    3.91611  43.58528   
1                180    4.04194  43.64694   
2                543    3.03167  43.36028   
3                545    3.03278  43.36167   
4                850    3.56444  43.64583   
5                851    3.56306  43.64806   
6                852    3.56306  43.64694   
7               1072    3.91611  43.58500   
8               1073    3.91667  43.58667   
9               1074    3.91889  43.58583   
10              1115    3.20806  43.34861   
11              1193    3.89750  43.63806   
12              1194    3.89778  43.63889   
13              1195    3.89889  43.63861   
14              1955    3.88556  43.71639   
15              2286    3.86944  43.60833   
16              2428    4.08361  43.55861   
17              2429    4.08361  43.55861   
18              3043    3.23056  43.36139   
19              3045    3.23028  43.36167   
20              3046    3.22861  43.36306   
21        

In [19]:
#  pour faire une simplification  ona choisir z avec les 2 colonnes suivantes se et z avec le vecteur target
Z=df1[['Numéro de mesure','Niveau_global']].to_numpy()
print(Z)
z=df1['target'].to_numpy()
print(z)

[[1.750e+02 0.000e+00]
 [1.800e+02 1.000e-02]
 [5.430e+02 5.540e+00]
 [5.450e+02 5.200e+00]
 [8.500e+02 4.530e+00]
 [8.510e+02 5.780e+00]
 [8.520e+02 3.530e+00]
 [1.072e+03 3.000e+00]
 [1.073e+03 4.540e+00]
 [1.074e+03 2.000e+00]
 [1.115e+03 1.000e+00]
 [1.193e+03 1.350e+00]
 [1.194e+03 1.470e+00]
 [1.195e+03 5.700e-01]
 [1.955e+03 6.950e+00]
 [2.286e+03 7.400e+00]
 [2.428e+03 9.630e+00]
 [2.429e+03 8.160e+00]
 [3.043e+03 1.000e+01]
 [3.045e+03 2.000e+01]
 [3.046e+03 3.000e+01]
 [3.047e+03 1.000e+01]
 [3.261e+03 2.000e+01]
 [3.263e+03 3.000e+01]
 [3.309e+03 6.950e+00]
 [3.310e+03 7.950e+00]
 [3.876e+03 6.100e+00]
 [3.877e+03 3.000e+01]
 [3.878e+03 9.000e+00]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [20]:
#créer une fonction pour associer à chaque niveau un target qui lui correspond

def target():
    for t in range(0,len(df1)):
        if df1['Niveau_global'][t] > 6 :
            df1['target'][t] = 0
            print(df1['Niveau_global'][t])

In [21]:
target()

6.95
7.4
9.63
8.16
10.0
20.0
30.0
10.0
20.0
30.0
6.95
7.95
6.1
30.0
9.0


<ipython-input-20-822d0b5b1374>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['target'][t] = 0


In [22]:
pd.crosstab(df1.target, "freq")

col_0   freq
target      
0         15
1         14

In [23]:
#prédicter y1 et le comparer avec z target
y1_pred=logreg1.predict(Z)
print(y1_pred)

[1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [24]:
#afficher la matrice de confusion
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(z,y1_pred))
print(classification_report(z,y1_pred))
print(accuracy_score(z, y1_pred))

[[15  0]
 [ 1 13]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        15
           1       1.00      0.93      0.96        14

    accuracy                           0.97        29
   macro avg       0.97      0.96      0.97        29
weighted avg       0.97      0.97      0.97        29

0.9655172413793104


####  == J'ai obtenu une precision égale 0.96

In [25]:
#pickle.dump( df, open( "datasave.p", "wb" ) )


### à l'aide de cette commande j'ai enregistré le meilleure dataset aprés pleusieure execution, car les valeures ne sont pas stable grace au random 